name:                halite
version:             0.1.0.0
github:              "loovjo/halite"
license:             BSD3
author:              "Jonathan Lööv"
maintainer:          "example@example.com"
copyright:           "2019 "

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A simple Haskell-inspired language

dependencies:
- base >= 4.7 && < 5
- text >= 1.2 && < 1.3

library:
  source-dirs: src

executables:
  halite-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - halite

tests:
  halite-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - halite
